### ISSUE TITLE
Missing exception messages on Windows UWP

### ISSUE THREAD

**Issue by DanielSWolf** [mobilexag/cordova-sqlite-evplus-ext-free#22]
Errors returned by the UWP plugin contain fewer information than on other platforms. For example, on most platforms, a syntax error will result in the error message "Error: near "from": syntax error". On UWP, we get the more generic "Error preparing an SQLite statement.".

This should be fixed so that error messages are identical on all platforms.

**Comment by DanielSWolf** [comment]
Internal ticket: https://yt.mobilexag.de/issue/PRDXMIP-1032

Old ID: 19.6 (UWP error messages)

**Comment by brody2consult** [comment]
This should be fixed by PR #18, looking forward to your validation.

As I said in PR #18, the error info is still not consistent in case of constraint violation on Windows. I would like to deal with this case in issue #25.

**Comment by brody2consult** [comment]
Now fixed, as discussed in PR #18, leaving constraint violation error info to be tracked separately in issue #25.
