### ISSUE TITLE
Custom upper() function gives wrong results

### ISSUE THREAD

**Issue by DanielSWolf** [mobilexag/cordova-sqlite-evplus-ext-free#34]
This repo contains a custom `upper()` function, implemented in #21. We just discovered that there are three characters that aren't handled correctly in this function. It seems that this is my fault, as these errors are contained in the original character table I gave you in #21.

@brodybits This bug isn't critical by any means. Maybe it could be fixed in the course of porting our custom features to the official repo.

| Input | Output | Expected |
|---|---|---|
| đ (Latin Small Letter D with Stroke, U+0111) | Ď (Latin Capital Letter D with Caron, U+010E) | Đ (Latin Capital Letter D with Stroke, U+0110) |
| ď (Latin Small Letter D with Caron, U+010F) | Đ (Latin Capital Letter D with Stroke, U+0110) | Ď (Latin Capital Letter D with Caron, U+010E) |
| ð (Latin Small Letter Eth, U+00F0) | Đ (Latin Capital Letter D with Stroke, U+0110) | Ð (Latin Capital Letter Eth*, U+00D0) |

*Note: "Latin Capital Letter D with Stroke" and "Latin Capital Letter Eth" are visually identical, but have different Unicode code points.

We're tracking this issue internally as PRDXMIP-2391.

**Comment by brody2consult** [comment]
Hi @DanielSWolf I **just** found this ticket. My apologies for the delay.

I may need some time to double-check my understanding of this issue before working on a solution.

As you may know, the code would need to be updated in this project: https://github.com/brodybits/sqlite3-eu

This means that I *may* be able to get this fixed in this repo ... which could expedite the validation from your side.

**Comment by DanielSWolf** [comment]
Hi @brodybits,

No problem about the delay. Thanks for looking into it!

**Comment by DanielSWolf** [comment]
The fix should be as easy as changing the three incorrect Unicode code points in your lookup table. I've just created a PR: https://github.com/brodybits/sqlite3-eu/pull/1

**Comment by brody2consult** [comment]
Thanks @DanielSWolf for contributing the quick solution ... just merged!

I am now reopening this issue with some TODO items:

- [x] rebuild Android NDK library with this bug fix
- [x] test on all supported platforms Android, iOS, and now deprecated platforms Windows, macOS
- [ ] add UPPER character tests to the test suite in main cordova-sqlite-storage plugin version, to be eventually merged into this and other plugin forks
